name: shams_pdf_editor
description: Standalone Shams PDF editor for Android, iOS and browsers.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdf: 34.2.8
  syncfusion_flutter_pdfviewer: 34.2.8
  file_picker: 13.1.0
  http: ^1.5.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.jpeg"
  min_sdk_android: 21
